[project]
name = "namaste-icd11-fhir-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fhir-resources>=8.1.0",
    "httpx>=0.28.1",
]
